project('testdisk++', 'cpp', version: '0.1.0-WIP')

compiler = meson.get_compiler('cpp')

conf_data = configuration_data()
conf_data.set('version', meson.project_version())
conf_data.set('testdiskdate', 'July 2026')
conf_data.set('target', host_machine.system())
conf_data.set('compiler_id', compiler.get_id())
conf_data.set('compiler_version', compiler.version())
configure_file(input: 'config.h.in', output: 'config.h', configuration: conf_data)

spdlog_dep = dependency(
  'spdlog',
  version: '1.17.0',
  fallback: ['spdlog', 'spdlog_dep'],
  required: true,
)

inc_dirs = include_directories('include')
sources = files(
  'src/addpart.cpp',
  'src/adv.cpp',
  'src/analyse.cpp',
  'src/askloc.cpp',
  'src/autoset.cpp',
  'src/chgtype.cpp',
  'src/common.cpp',
  'src/crc.cpp',
  'src/dimage.cpp',
  'src/dir.cpp',
  'src/dirpart.cpp',
  'src/fnctdsk.cpp',
  'src/hdaccess.cpp',
  'src/hdcache.cpp',
  'src/hidden.cpp',
  'src/hpa_doc.cpp',
  'src/intrf.cpp',
  'src/intrface.cpp',
  'src/io_redir.cpp',
  'src/log.cpp',
  'src/log_part.cpp',
  'src/part/apfs.cpp',
  'src/part/apfs_common.cpp',
  'src/part/bfs.cpp',
  'src/part/bsd.cpp',
  'src/part/btrfs.cpp',
  'src/part/cramfs.cpp',
  'src/part/ex2_sbn.cpp',
  'src/part/exfat.cpp',
  'src/part/exfat_dir.cpp',
  'src/part/ext2.cpp',
  'src/part/ext2_common.cpp',
  'src/part/ext2_dir.cpp',
  'src/part/ext2_sb.cpp',
  'src/part/f2fs.cpp',
  'src/part/fat.cpp',
  'src/part/fat1x.cpp',
  'src/part/fat32.cpp',
  'src/part/fat_adv.cpp',
  'src/part/fat_cluster.cpp',
  'src/part/fat_common.cpp',
  'src/part/fat_dir.cpp',
  'src/part/fatx.cpp',
  'src/part/gfs.cpp',
  'src/part/hfs.cpp',
  'src/part/hfsp.cpp',
  'src/part/hpfs.cpp',
  'src/part/iso.cpp',
  'src/part/jfs.cpp',
  'src/part/luks.cpp',
  'src/part/lvm.cpp',
  'src/part/md.cpp',
  'src/part/netware.cpp',
  'src/part/ntfs.cpp',
  'src/part/ntfs_adv.cpp',
  'src/part/ntfs_dir.cpp',
  'src/part/ntfs_fix.cpp',
  'src/part/ntfs_udl.cpp',
  'src/part/partgpt.cpp',
  'src/part/partgpto.cpp',
  'src/part/parthumax.cpp',
  'src/part/parti386.cpp',
  'src/part/partmac.cpp',
  'src/part/partnone.cpp',
  'src/part/partsun.cpp',
  'src/part/partxbox.cpp',
  'src/part/refs.cpp',
  'src/part/rfs.cpp',
  'src/part/rfs_dir.cpp',
  'src/part/sun.cpp',
  'src/part/swap.cpp',
  'src/part/sysv.cpp',
  'src/part/texfat.cpp',
  'src/part/thfs.cpp',
  'src/part/tntfs.cpp',
  'src/part/ufs.cpp',
  'src/part/vmfs.cpp',
  'src/part/wbfs.cpp',
  'src/part/xfs.cpp',
  'src/part/zfs.cpp',
  'src/partauto.cpp',
  'src/savehdr.cpp',
  'src/setdate.cpp',
  'src/testdisk.cpp',
  'src/ui/tlog.cpp',
  'src/unicode.cpp',
  'src/ui/tdisksel.cpp',
  'src/utils.cpp',
)

executable(
  'testdisk',
  sources,
  include_directories: inc_dirs,
  dependencies: [spdlog_dep],
)
